"""Branded DOCX report generation and client-profile persistence.

Client profiles (logo path, brand colours, name, footer) are stored as JSON on
disk so they survive between sessions. The report itself is assembled with
python-docx from a :class:`ReportSpec` that the app populates with pre-rendered
chart PNGs and text — keeping this module free of any plotting/analysis logic.
"""

from __future__ import annotations

import io
import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Inches, Pt, RGBColor

from sentiment import DISCLAIMER, NEGATIVE, NEUTRAL, POSITIVE

PROFILE_DIR = Path(__file__).parent / "profiles"
DEFAULT_PRIMARY = "#1F4E79"
DEFAULT_SECONDARY = "#E8A33D"


# --------------------------------------------------------------------------- #
# Client profiles
# --------------------------------------------------------------------------- #
@dataclass
class ClientProfile:
    client_name: str = "Client"
    primary: str = DEFAULT_PRIMARY
    secondary: str = DEFAULT_SECONDARY
    footer: str = ""
    logo_path: Optional[str] = None

    def slug(self) -> str:
        return re.sub(r"[^a-z0-9]+", "-", self.client_name.lower()).strip("-") or "client"


def _ensure_dir() -> None:
    PROFILE_DIR.mkdir(parents=True, exist_ok=True)


def save_profile(profile: ClientProfile) -> Path:
    _ensure_dir()
    path = PROFILE_DIR / f"{profile.slug()}.json"
    path.write_text(json.dumps(asdict(profile), indent=2))
    return path


def list_profiles() -> list[str]:
    if not PROFILE_DIR.exists():
        return []
    return sorted(p.stem for p in PROFILE_DIR.glob("*.json"))


def load_profile(slug: str) -> Optional[ClientProfile]:
    path = PROFILE_DIR / f"{slug}.json"
    if not path.exists():
        return None
    try:
        return ClientProfile(**json.loads(path.read_text()))
    except (json.JSONDecodeError, TypeError):
        return None


# --------------------------------------------------------------------------- #
# Report spec
# --------------------------------------------------------------------------- #
@dataclass
class SentimentBlock:
    distribution: dict[str, int]
    quotes: dict[str, list[str]]
    keywords: list[tuple[str, int]]
    dist_png: Optional[bytes] = None


@dataclass
class ChartSection:
    title: str
    png: Optional[bytes] = None
    takeaways: list[str] = field(default_factory=list)
    sentiment: Optional[SentimentBlock] = None


@dataclass
class ReportSpec:
    title: str
    subtitle: str = ""
    sections: list[ChartSection] = field(default_factory=list)
    trend_sections: list[ChartSection] = field(default_factory=list)
    future_questions: list[str] = field(default_factory=list)
    data_quality: list[str] = field(default_factory=list)
    event_summary: list[str] = field(default_factory=list)


# --------------------------------------------------------------------------- #
# DOCX helpers
# --------------------------------------------------------------------------- #
def _rgb(hex_colour: str) -> RGBColor:
    return RGBColor.from_string(hex_colour.lstrip("#").upper())


def _shade_paragraph(paragraph, hex_colour: str) -> None:
    """Apply a solid background fill to a paragraph (used for the cover banner)."""
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_colour.lstrip("#").upper())
    paragraph.paragraph_format.element.get_or_add_pPr().append(shd)


def _coloured_heading(doc: Document, text: str, level: int, colour: str) -> None:
    heading = doc.add_heading(level=level)
    run = heading.add_run(text)
    run.font.color.rgb = _rgb(colour)


def _add_image(doc: Document, png: bytes, width_in: float = 6.0) -> None:
    doc.add_picture(io.BytesIO(png), width=Inches(width_in))


def _add_footer(doc: Document, profile: ClientProfile) -> None:
    section = doc.sections[0]
    footer = section.footer
    para = footer.paragraphs[0]
    para.text = profile.footer or f"{profile.client_name} — generated by CUIGG Reporting"
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in para.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = _rgb(profile.secondary)


def _sentiment_block(doc: Document, block: SentimentBlock, profile: ClientProfile) -> None:
    p = doc.add_paragraph()
    run = p.add_run(DISCLAIMER)
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = _rgb(profile.secondary)

    total = sum(block.distribution.values()) or 1
    summary = "  ·  ".join(
        f"{label}: {block.distribution.get(label, 0)} ({100 * block.distribution.get(label, 0) / total:.0f}%)"
        for label in (POSITIVE, NEUTRAL, NEGATIVE)
    )
    doc.add_paragraph(summary)

    if block.dist_png:
        _add_image(doc, block.dist_png, width_in=4.5)

    if block.keywords:
        kw = ", ".join(f"{w} ({c})" for w, c in block.keywords[:8])
        doc.add_paragraph(f"Top themes: {kw}")

    for label in (POSITIVE, NEUTRAL, NEGATIVE):
        quotes = block.quotes.get(label, [])
        if not quotes:
            continue
        doc.add_paragraph(f"Representative {label.lower()} comments:", style="Intense Quote")
        for q in quotes:
            doc.add_paragraph(f"“{q}”", style="List Bullet")


# --------------------------------------------------------------------------- #
# Main entry point
# --------------------------------------------------------------------------- #
def generate_docx(profile: ClientProfile, spec: ReportSpec) -> bytes:
    """Assemble the full branded report and return it as DOCX bytes."""
    doc = Document()

    # ---- Cover page ----
    if profile.logo_path and Path(profile.logo_path).exists():
        try:
            doc.add_picture(profile.logo_path, width=Inches(2.5))
            doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
        except Exception:  # pragma: no cover - bad image shouldn't break report
            pass

    banner = doc.add_paragraph()
    banner.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _shade_paragraph(banner, profile.primary)
    run = banner.add_run(f"  {profile.client_name}  ")
    run.bold = True
    run.font.size = Pt(26)
    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    tr = title_p.add_run(spec.title)
    tr.font.size = Pt(20)
    tr.font.color.rgb = _rgb(profile.primary)

    if spec.subtitle:
        sub = doc.add_paragraph()
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sr = sub.add_run(spec.subtitle)
        sr.font.size = Pt(12)
        sr.font.color.rgb = _rgb(profile.secondary)

    if spec.event_summary:
        doc.add_paragraph()
        for line in spec.event_summary:
            doc.add_paragraph(line, style="List Bullet")

    doc.add_page_break()

    # ---- Per-question sections ----
    _coloured_heading(doc, "Survey results", 1, profile.primary)
    for section in spec.sections:
        _coloured_heading(doc, section.title, 2, profile.secondary)
        if section.png:
            _add_image(doc, section.png)
        if section.takeaways:
            doc.add_paragraph("Key takeaways:", style="Heading 3")
            for t in section.takeaways:
                doc.add_paragraph(t, style="List Bullet")
        if section.sentiment:
            _sentiment_block(doc, section.sentiment, profile)
        doc.add_paragraph()

    # ---- Trends ----
    if spec.trend_sections:
        doc.add_page_break()
        _coloured_heading(doc, "Cross-event trends", 1, profile.primary)
        for section in spec.trend_sections:
            _coloured_heading(doc, section.title, 2, profile.secondary)
            if section.png:
                _add_image(doc, section.png)
            for t in section.takeaways:
                doc.add_paragraph(t, style="List Bullet")
            doc.add_paragraph()

    # ---- Future questions ----
    if spec.future_questions:
        doc.add_page_break()
        _coloured_heading(doc, "Recommended questions for next time", 1, profile.primary)
        for q in spec.future_questions:
            doc.add_paragraph(q, style="List Bullet")

    # ---- Data quality appendix ----
    doc.add_page_break()
    _coloured_heading(doc, "Appendix — data quality & cleaning", 1, profile.primary)
    doc.add_paragraph(
        "The following automated, deterministic cleaning steps were applied to the "
        "raw export. No data was silently dropped."
    )
    for line in spec.data_quality:
        doc.add_paragraph(re.sub(r"\*\*", "", line), style="List Bullet")

    _add_footer(doc, profile)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
